export const GET_USER_LIST = 'GET_USER_LIST';
export const GET_REPOSITORY_DETAILS = 'GET_REPOSITORY_DETAILS';
export const CLEAN_REPOSITORY_DETAILS = 'CLEAN_REPOSITORY_DETAILS';
export const SORT_USER_LIST = 'SORT_USER_LIST';